version: 0.2

phases:
  # pre_build:
  #   commands:
  #     - echo Logging in to Amazon ECR...
  #     - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t escrow-app:latest .
      - docker tag escrow-app:latest 305551176518.dkr.ecr.us-west-1.amazonaws.com/escrow-app:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 305551176518.dkr.ecr.us-west-1.amazonaws.com/escrow-app:latest
artifacts:
  files:
    - scripts/start_container.sh
    - appspec.yml
  discard-paths: yes
